local M = {}

local function insert_lines(bufnr, lines)
  vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, lines)
end

local function insert_at_cursor(bufnr, lines)
  local row = vim.api.nvim_win_get_cursor(0)[1]
  vim.api.nvim_buf_set_lines(bufnr, row, row, false, lines)
  vim.api.nvim_win_set_cursor(0, { row + #lines, 0 })
end

local function adi_field(name, value)
  return string.format("<%s:%d>%s", name, #value, value)
end

function M.create_adi_file()
  vim.api.nvim_command("enew")
  local bufnr = vim.api.nvim_get_current_buf()

  local header = {
    "Generated by vi adi v1.0",
    "<ADIF_VER:5>3.1.4 <EOH>",
    "",
  }

  insert_lines(bufnr, header)
  vim.api.nvim_win_set_cursor(0, { #header + 1, 0 })
end

function M.start_qso_entry()
  local call = vim.fn.input("Callsign: ")
  if call == "" then
    return
  end

  local band = vim.fn.input("Band (e.g. 2m, 20m): ")
  if band == "" then
    return
  end

  local mode = vim.fn.input("Mode (e.g. FM, SSB): ")
  if mode == "" then
    return
  end

  local rst_sent = vim.fn.input("RST Sent: ")
  if rst_sent == "" then
    return
  end

  local rst_rcvd = vim.fn.input("RST Rcvd: ")
  if rst_rcvd == "" then
    return
  end

  local comment = vim.fn.input("Comment: ")
  if comment == "" then
    return
  end

  local qso_date = os.date("!%Y%m%d")
  local time_on = os.date("!%H%M")

  local line1 = table.concat({
    adi_field("QSO_DATE", qso_date),
    adi_field("TIME_ON", time_on),
    adi_field("CALL", call),
  }, " ")

  local line2 = table.concat({
    adi_field("BAND", band),
    adi_field("MODE", mode),
    adi_field("RST_SENT", rst_sent),
    adi_field("RST_RCVD", rst_rcvd),
  }, " ")

  local line3 = table.concat({
    adi_field("COMMENT", comment),
    "<EOR>",
  }, " ")

  local bufnr = vim.api.nvim_get_current_buf()
  insert_at_cursor(bufnr, { line1, line2, line3 })
end

function M.setup()
  vim.keymap.set("n", "<leader>adi", M.create_adi_file, {
    desc = "Create new ADI file with header",
  })

  vim.keymap.set("n", "<leader>adi:qso", M.start_qso_entry, {
    desc = "Start a new QSO entry",
  })
end

return M
